# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
